### PR TITLE
Add CDandLP in contextual menu options

### PR DESCRIPTION
**Pull request by aknorw**
Add [CDandLP](https://www.cdandlp.com/) to contextual menu options.
Largely inspired by https://github.com/salcido/discogs-enhancer/pull/194.
Successfully tested locally.

### CODE REVIEW

**Comment by salcido** [comment]
@aknorw Thanks! I won't have a chance to check this out until later this week but looks great at first glance 👍

**Comment by salcido** [comment]
Can you update so that the version number is not bumped up to 3.0.19? I have some other changes I'm working on that I want to roll out for 3.0.19.

**Comment by aknorw** [comment]
> Can you update so that the version number is not bumped up to 3.0.19? I have some other changes I'm working on that I want to roll out for 3.0.19.

Done!

**Review by salcido — APPROVED** [review]
Looks great! Thanks for taking the time to put this together 🎉

**Pull request merged**
